import PDFDocument from 'pdfkit'

export interface AgencyPdfPayload {
  copyrightCode: string
  songTitle: string
  creatorRealName: string | null
  creatorPhone: string
  agencySignedAt: Date | null
  isrc: string | null
  issueDate: Date
}

/**
 * 生成"代理发行授权凭证" PDF（简化版模板）。
 * 返回 Buffer，调用方可直接 Response body 返回或塞进 ZIP。
 *
 * 正式授权书的法律条款需法务审核，这里按 PRD §7.3.7 建一个可打印模板。
 */
export async function buildAgencyPdf(p: AgencyPdfPayload): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 })
      const chunks: Buffer[] = []
      doc.on('data', (c) => chunks.push(c as Buffer))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      // 标题
      doc.fontSize(20).text('Music Copyright Agency Authorization', { align: 'center' })
      doc.moveDown(0.3)
      doc.fontSize(12).fillColor('#64748b').text('(Version v1.0)', { align: 'center' })
      doc.moveDown(1.5)

      // 作品信息
      doc.fillColor('#000').fontSize(13).text('Work Info', { underline: true })
      doc.moveDown(0.3)
      doc.fontSize(11)
      const kv = (k: string, v: string) => { doc.text(`${k}: ${v}`) }
      kv('Title', p.songTitle)
      kv('Copyright Code', p.copyrightCode)
      kv('ISRC', p.isrc ?? '(pending)')
      kv('Creator', p.creatorRealName ?? '(not set)')
      kv('Phone', p.creatorPhone)
      kv('Signed At', p.agencySignedAt ? p.agencySignedAt.toISOString().slice(0, 10) : '(not signed)')
      kv('Issue Date', p.issueDate.toISOString().slice(0, 10))
      doc.moveDown(1.2)

      // 授权条款（模板）
      doc.fontSize(13).text('Authorization', { underline: true })
      doc.moveDown(0.3)
      doc.fontSize(10).fillColor('#111').text(
        'The creator named above hereby authorizes the Platform as the exclusive agent to distribute the above-mentioned work to music streaming services and short-video platforms, including but not limited to QQ Music, NetEase Cloud Music, Spotify, Apple Music, Kugou, Douyin, Soda Music. The Platform is entitled to manage revenue collection, settlement, and reporting on behalf of the creator under the commission ratio defined in the platform settings.',
        { align: 'justify' },
      )
      doc.moveDown(0.5)
      doc.text(
        'This certificate is issued automatically upon release confirmation and serves as proof of the agency relationship. All rights and obligations are further governed by the Music Agency Distribution Agreement signed by the creator.',
        { align: 'justify' },
      )
      doc.moveDown(2)

      // 签署区
      doc.fontSize(11)
      doc.text('Platform Seal:  _______________________', 50, undefined)
      doc.moveDown(0.8)
      doc.text('Creator Sign: _______________________')
      doc.moveDown(1.2)
      doc.fontSize(9).fillColor('#94a3b8').text('Generated by Museek Platform · Auto-issued', { align: 'center' })

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}
